### PR TITLE
Center

### PR DESCRIPTION
**Pull request by acircleda**
Made a minor change to fix the exampls.

### CODE REVIEW

**Review by lrocconi — APPROVED** [review]

**Review by lrocconi — APPROVED** [review]

**Review by lrocconi — CHANGES_REQUESTED** [review]
updated in previous pull request

**Comment by acircleda** [comment]
For this one, somehow the robust_se.R got attached, but there were a few changes in center.R. Have those been updated?

**Review by lrocconi — APPROVED** [review]
approve. how do I merge changes for this one function?

**Comment by lrocconi** [comment]
Should I close this request and open a new one with just the center files?

**Comment by acircleda** [comment]
The changes to center.R are minor, so you could just copy and paste the code to main and ignore the pull request and delete the branch. That might be easiest.


Anthony Schmidt
he/him/his


PhD Student - Evaluation, Statistics, & Measurement

College of Education, Health, and Human Sciences

The University of Tennessee, Knoxville

-----------------------------------------

@anthonyteacher<https://twitter.com/AnthonyTeacher>

http://www.anthonyschmidt.co<http://www.anthonyschmidt.co/>

________________________________

**Comment by lrocconi** [comment]
manually updated changes to center.R

**Pull request closed without merging**
